// Code generated by sqlc. DO NOT EDIT.
// source: attendance.sql

package db

import (
	"context"
	"time"
)

const createAttendance = `-- name: CreateAttendance :one
INSERT INTO attendance(
    student,
    course_code,
    mark_student,
    last_attendance
) VALUES (
    $1, $2, $3, $4
) RETURNING id, student, course_code, mark_student, last_attendance, created_at
`

type CreateAttendanceParams struct {
	Student        string    `json:"student"`
	CourseCode     string    `json:"course_code"`
	MarkStudent    bool      `json:"mark_student"`
	LastAttendance time.Time `json:"last_attendance"`
}

func (q *Queries) CreateAttendance(ctx context.Context, arg CreateAttendanceParams) (Attendance, error) {
	row := q.db.QueryRowContext(ctx, createAttendance,
		arg.Student,
		arg.CourseCode,
		arg.MarkStudent,
		arg.LastAttendance,
	)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.Student,
		&i.CourseCode,
		&i.MarkStudent,
		&i.LastAttendance,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttendance = `-- name: DeleteAttendance :exec
DELETE FROM attendance
WHERE id = $1
`

func (q *Queries) DeleteAttendance(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAttendance, id)
	return err
}

const getAttendance = `-- name: GetAttendance :one
SELECT id, student, course_code, mark_student, last_attendance, created_at FROM attendance
WHERE id = $1
`

func (q *Queries) GetAttendance(ctx context.Context, id int64) (Attendance, error) {
	row := q.db.QueryRowContext(ctx, getAttendance, id)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.Student,
		&i.CourseCode,
		&i.MarkStudent,
		&i.LastAttendance,
		&i.CreatedAt,
	)
	return i, err
}

const listAttendance = `-- name: ListAttendance :many
SELECT id, student, course_code, mark_student, last_attendance, created_at FROM attendance
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListAttendanceParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAttendance(ctx context.Context, arg ListAttendanceParams) ([]Attendance, error) {
	rows, err := q.db.QueryContext(ctx, listAttendance, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attendance{}
	for rows.Next() {
		var i Attendance
		if err := rows.Scan(
			&i.ID,
			&i.Student,
			&i.CourseCode,
			&i.MarkStudent,
			&i.LastAttendance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttendance = `-- name: UpdateAttendance :one
UPDATE attendance
SET student = $2, course_code = $3, mark_student = $4, last_attendance = $5
WHERE id = $1
RETURNING id, student, course_code, mark_student, last_attendance, created_at
`

type UpdateAttendanceParams struct {
	ID             int64     `json:"id"`
	Student        string    `json:"student"`
	CourseCode     string    `json:"course_code"`
	MarkStudent    bool      `json:"mark_student"`
	LastAttendance time.Time `json:"last_attendance"`
}

func (q *Queries) UpdateAttendance(ctx context.Context, arg UpdateAttendanceParams) (Attendance, error) {
	row := q.db.QueryRowContext(ctx, updateAttendance,
		arg.ID,
		arg.Student,
		arg.CourseCode,
		arg.MarkStudent,
		arg.LastAttendance,
	)
	var i Attendance
	err := row.Scan(
		&i.ID,
		&i.Student,
		&i.CourseCode,
		&i.MarkStudent,
		&i.LastAttendance,
		&i.CreatedAt,
	)
	return i, err
}
