// Code generated by sqlc. DO NOT EDIT.
// source: department.sql

package db

import (
	"context"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO department(
    department_id, 
    school
) VALUES(
    $1, $2
) RETURNING department_id, school, created_at
`

type CreateDepartmentParams struct {
	DepartmentID string `json:"department_id"`
	School       string `json:"school"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRowContext(ctx, createDepartment, arg.DepartmentID, arg.School)
	var i Department
	err := row.Scan(&i.DepartmentID, &i.School, &i.CreatedAt)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM department
WHERE department_id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, departmentID string) error {
	_, err := q.db.ExecContext(ctx, deleteDepartment, departmentID)
	return err
}

const getDepartment = `-- name: GetDepartment :one
SELECT department_id, school, created_at FROM department 
WHERE department_id = $1
`

func (q *Queries) GetDepartment(ctx context.Context, departmentID string) (Department, error) {
	row := q.db.QueryRowContext(ctx, getDepartment, departmentID)
	var i Department
	err := row.Scan(&i.DepartmentID, &i.School, &i.CreatedAt)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT department_id, school, created_at FROM department
ORDER BY department_id
LIMIT $1
OFFSET $2
`

type ListDepartmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]Department, error) {
	rows, err := q.db.QueryContext(ctx, listDepartments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(&i.DepartmentID, &i.School, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE department
SET school = $2
WHERE department_id = $1
RETURNING department_id, school, created_at
`

type UpdateDepartmentParams struct {
	DepartmentID string `json:"department_id"`
	School       string `json:"school"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRowContext(ctx, updateDepartment, arg.DepartmentID, arg.School)
	var i Department
	err := row.Scan(&i.DepartmentID, &i.School, &i.CreatedAt)
	return i, err
}
